### ISSUE TITLE
Update Cutlass Version

### ISSUE THREAD

**Issue by tgrogers** [accel-sim/gpu-app-collection#15]
Update required for Cutlass version from 2 to 3. After the update, the cutlass version 3 kernels should be traced and executed with accel-sim. 

More information on changes in cutlass 3 are found here: https://github.com/NVIDIA/cutlass

**Comment by Shreya-gaur** [comment]
1. The cutlass 3 can now be built with the Makefile in gpu-app-collection repository.
2. The cutlass profiler is updated from cutlass_perf_test to cutlass_profiler executable.
3. The define-all-apps.yml and define-power.yml in util/job_launching/app have been updated to reflect the arguments changed in cutlass 3.
Note: Changes yet to be pushed
